Login logic change
DSM-DMS/DMS-Front-V3 pull request #83
Opened 2019-06-16 12:42 UTC by gtobio11

2019-06-16 13:57 UTC, khg0712 requested changes

2019-06-16 13:57 UTC, khg0712 commented on src/student/container/Main/Meal/MealContainer.js
> +    const getFormDate = `${selectedDate.getFullYear()}-${
이건 따로 util 함수로 빼는 게 좋지 않을까요?

2019-06-17 00:39 UTC, SeungYongSon commented
제가 왜 리뷰어인 부분????

2019-06-17 14:38 UTC, leafcis commented on src/student/container/Main/Meal/MealContainer.js
> +    const getFormDate = `${selectedDate.getFullYear()}-${
동의합니다

2019-06-17 14:38 UTC, leafcis commented on src/student/container/Main/Meal/MealContainer.js
> +    const getFormDate = `${selectedDate.getFullYear()}-${
동의합니다

2019-06-18 14:08 UTC, merged